### ISSUE TITLE
RuntimeError: Invalid checksum for file MACS.yaml

### ISSUE THREAD

**Issue by 980202006** [Labbeti/aac-datasets#2]
I tried to download clotho and macs data sets using aac-datasets-download --root "." macs, and encountered the problem RuntimeError: Invalid checksum for file MACS.yaml. After downloading macs.yaml

**Comment by Labbeti** [comment]
Hi!
Can you try to remove manually this file and re-run the command again?
It should be located in `./MACS/MACS.yaml`

**Comment by 980202006** [comment]
Yes.It worked.Thank you!
